### ISSUE TITLE
After a "snap remove playlist-dl" and "snap install playlist-dl" license is gone

### ISSUE THREAD

**Issue by abrighton** [keshavbhatt/playlist-dl#2]
After a "snap remove playlist-dl" followed by a "snap install playlist-dl", the paid for lifetime license is gone.
The "Unclock" (Should be "Unlock") button and "Restore Account" buttons do not restore the account.
There should be a way to restore the account that was paid for!

**Comment by keshavbhatt** [comment]
Hi Please make an email to 98378sub@gmail.com providing your new account ID for restoration.
