### ISSUE TITLE
data doesnt refresh

### ISSUE THREAD

**Issue by itsdarkerinnit** [keshavbhatt/playlist-dl#3]
Hi, 
I've been trying to download a playlist whose content was updated but playlist-dl doesnt seem to be absorbing the changes and is still presenting me with a previous version of said playlist.

I've tried to clear cache but the button doesnt seem to be doing anything.

I installed via Snap and i've search and can't seem to find where playlist-dl is storing  cache.  I need to go for a manual cleaning so that it sees the playlist in full, correct? Can you point me in the right direction please? System is Ubuntu based.

**Comment by itsdarkerinnit** [comment]
before any of this I had bought the lifetime license if that matters. 
Would love to hear back  from you when you can @keshavbhatt

**Comment by keshavbhatt** [comment]
@itsdarkerinnit I am sorry for replying you late. 
The path is `~/snap/playlist-dl/current/.local/share/org.keshavnrj.ubuntu/Playlist DL/playlist_cache/`

(`~/` means logged in user's home directory.)

Thanks for bringing this to my attention, I will try to fix that in upcoming version.

**Comment by itsdarkerinnit** [comment]
No problem @keshavbhatt, and  I apprectiate you making this app.

After clearing the cache manually it is working now as intended. I dont know how I missed the local snap dir 👀 🤦🏻‍♂️ 

 Thank you!

**Comment by keshavbhatt** [comment]
@itsdarkerinnit I have **added a button to force reload** from network in **Playlist-dl version 2.2** available now in snap store (run `snap refresh playlist-dl` or update from appstore to get it):

![image](https://github.com/user-attachments/assets/a54c68d3-cbe0-47da-815e-e8fbbd139a67)

A similar button is also available in Playlist search view as well to bypass the cache:

![image](https://github.com/user-attachments/assets/87616041-41e8-4dc9-bbd7-ed5abe9dfd70)

**Comment by itsdarkerinnit** [comment]
Amazing, thank you!
New release soon then 👀 👍🏻

**Comment by itsdarkerinnit** [comment]
My friend @keshavbhatt , sorry to be writing on this closed issue, but clear cache button still isn't working 


Unrelated but i'm also waiting on a reply to a email I sent regarding license transfer because  i had to swap distro and trial time is about to run out before EOY.

Thank you.

Running on Nobara 40

Edit: typo's and OS

**Comment by keshavbhatt** [comment]
Hi @itsdarkerinnit , i am sorry for the inconvenience. Can you write me again via email if there is any activation or restoration related issue. About the issue in application, i will try tk reproduce the issue and provide a fix ASAP. 

Thanks

**Comment by itsdarkerinnit** [comment]
Hi @keshavbhatt consider switching to `flatpak` for distribution instead of `snap`. usage of `snap` is at a all time low specially for desktops and in all honestly.. I installed it just for playlist-dl because most devs moved to `flatpak` at this point.

Also, if I may, I'd like to suggest: 

retry on failed tracks -- because sometimes its a ip issue and if the user is behind a vpn he can always switch and try again?
Audio volume normalizer -- when converting to audio only, allow the user to optionally normalize the volume so that the tracks all  have the same audio volume.

Also fyi, Delete Cache btn doesnt seem to be doing anything again.

**Comment by itsdarkerinnit** [comment]
ping @keshavbhatt
